export const PaymentTerms = {
    "tabname": "Payment Terms",
    "value": 5,
    "fields": [
        {
            "name": "paymentMade",
            "label": "Payment To Be Made",
            "type": "select",
            "placeholder": "",
            "length": 4,
            "options": [
                { value: "advance", label: "Advance" },
                { value: "against delivery", label: "Against delivery" },
                { value: "50% advance", label: "50% advance" },
                { value: "other", label: "Other" },
            ]
        },
        {
            "name": "otherPaymentToBeMade",
            "label": "Any Other",
            "type": "text",
            "placeholder": "Specify Here",
            "length": 8,
        },
        {
            "name": "paymentMode",
            "label": "Payment Mode",
            "type": "select",
            "placeholder": "",
            "length": 4,
            "options": [
                { value: "Cheque", label: "Cheque" },
                { value: "Demand Draft", label: "Demand Draft" },
                { value: "NEFT", label: "NEFT" },
                { value: "RTGS", label: "RTGS" },
                { value: "Other", label: "Other" },
            ]
        },
        {
            "name": "otherPaymentMode",
            "label": "Any Other",
            "type": "text",
            "placeholder": "Specify Here",
            "length": 8,
        },
        {
            "name": "marginDeposit",
            "label": "Margin / Deposit mutually agreed",
            "type": "text",
            "placeholder": "Specify your payment mode",
            "length": 4,
        },
        {
            "name": "rtv",
            "label": "RTV",
            "type": "select",
            "placeholder": "",
            "length": 4,
            "options": [
                { value: true, label: "Yes" },
                { value: false, label: "No" },
            ]
        },
        {
            "name": "agreementExecuted",
            "label": "Agreement Executed",
            "type": "select",
            "placeholder": "",
            "length": 4,
            "options": [
                { value: true, label: "Yes" },
                { value: false, label: "No" },
            ]
        },
        {
            "name": "",
            "label": "Security Deposit Details",
            "type": "divider",
        },
        {
            "name": "securityDepoCheqNo",
            "label": "Cheque Number",
            "type": "text",
            "placeholder": "Cheque Number",
            "length": 6,
        },
        {
            "name": "securityDepoAmt",
            "label": "Amount",
            "type": "text",
            "placeholder": "Amount",
            "length": 6,
        },
        {
            "name": "lc",
            "label": "L/C",
            "type": "file",
            "placeholder": "",
            "length": 6,
        },
        {
            "name": "bg",
            "label": "B/G",
            "type": "file",
            "placeholder": "",
            "length": 6,
        },
        {
            "name": "",
            "label": "Initial Exposure Limit",
            "type": "divider",
        },
        {
            "name": "IELinAmt",
            "label": "In Amount",
            "type": "number",
            "placeholder": "In Amount",
            "length": 4,
        },
        {
            "name": "IELRecommendedBy",
            "label": "Recommended By",
            "type": "text",
            "placeholder": "In Amount",
            "length": 4,
        },
        {
            "name": "IELRecommendedDate",
            "label": "Recommended Date",
            "type": "date",
            "placeholder": "In Amount",
            "length": 4,
        },
        {
            "name": "",
            "label": "Revision of Exposure Limit",
            "type": "divider",
        },
        {
            "name": "RELinAmt",
            "label": "In Amount",
            "type": "number",
            "placeholder": "In Amount",
            "length": 4,
        },
        {
            "name": "RELRecommendedBy",
            "label": "Recommended By",
            "type": "text",
            "placeholder": "In Amount",
            "length": 4,
        },
        {
            "name": "RELRecommendedDate",
            "label": "Recommended Date",
            "type": "date",
            "placeholder": "In Amount",
            "length": 4,
        },
        {
            "name": "reason",
            "label": "Reason",
            "type": "text",
            "placeholder": "Specify Here",
            "length": 6,
        },
        {
            "name": "docEvidenceCopy",
            "label": "Documentary Evidence",
            "type": "file",
            "placeholder": "",
            "length": 6,
        },
    ]
}