import { Address, ICustomerKeyMobileNumbers } from '@prime-fresh/services';
import { convertInTitleCase, formatAddress } from '@prime-fresh/shared/modules';
import { formatDate, SectionConfig } from '../../../components';

export const CustomerFormPreviewConfig: SectionConfig[] = [
  {
    title: 'Customer Empanelment',
    sectionType: 'object',
    layout: 'grid',
    gridColumns: 3,
    fields: [
      {
        key: 'organisationName',
        label: 'Name of Organisation',
        render: (value: string) => (value ? convertInTitleCase(value) : '-'),
      },
      {
        key: 'customerTypes',
        label: 'Customer Type',
        render: (value: string) => (value ? convertInTitleCase(value) : '-'),
      },
      {
        key: 'customerCategory',
        label: 'Customer Category',
        render: (value: string) => (value ? convertInTitleCase(value) : '-'),
      },
      {
        key: 'organisationType',
        label: 'Organisation Type',
        render: (value: string) => (value ? convertInTitleCase(value) : '-'),
      },
      {
        key: 'primaryContactNo',
        label: 'Primary Contact Number',
        render: (value: string) => (value ? value : '-'),
      },
      {
        key: 'emailPrimary',
        label: 'Primary Email',
        render: (value: string) => (value ? value : '-'),
      },
      {
        key: 'secondaryContactNo',
        label: 'Alternate Contact Number',
        render: (value: string) => (value ? value : '-'),
      },
      {
        key: 'emailSecondary',
        label: 'Alternate Email',
        render: (value: string) => (value ? value : '-'),
      },
      {
        key: 'customerAddress',
        label: 'Customer Address',
        render: (value: Address) => (value ? formatAddress(value) : '-'),
      },
    ],
  },
  {
    title: 'Key Mobile Numbers',
    sectionType: 'object',
    layout: 'grid',
    gridColumns: 3,
    fields: [
      {
        key: '',
        label: 'Account Department Person Details',
        isHeader: true,
        width: 12,
      },
      {
        key: 'keyMobileNumbers.accDeptFName',
        label: 'First Name',
        width: 3,
        render: (value: string) => (value ? convertInTitleCase(value || '') : '-'),
      },
      {
        key: 'keyMobileNumbers.accDeptMName',
        label: 'Middle Name',
        width: 3,
        render: (value: string) => (value ? convertInTitleCase(value || '') : '-'),
      },
      {
        key: 'keyMobileNumbers.accDeptLName',
        label: 'Last Name',
        width: 3,
        render: (value: string) => (value ? convertInTitleCase(value || '') : '-'),
      },
      {
        key: 'keyMobileNumbers.accDeptMobileNo',
        label: 'Mobile Number',
        width: 3,
        render: (value: string) => (value ? value : '-'),
      },
      {
        key: '',
        label: 'Owner or decision Maker Details',
        isHeader: true,
        width: 12,
      },
      {
        key: 'keyMobileNumbers.ownerFName',
        label: 'First Name',
        width: 3,
        render: (value: string) => (value ? convertInTitleCase(value || '') : '-'),
      },
      {
        key: 'keyMobileNumbers.ownerMName',
        label: 'Middle Name',
        width: 3,
        render: (value: string) => (value ? convertInTitleCase(value || '') : '-'),
      },
      {
        key: 'keyMobileNumbers.ownerLName',
        label: 'Last Name',
        width: 3,
        render: (value: string) => (value ? convertInTitleCase(value || '') : '-'),
      },
      {
        key: 'keyMobileNumbers.ownerMobileNo',
        label: 'Mobile Number',
        width: 3,
        render: (value: string) => (value ? value : '-'),
      },
      {
        key: 'keyMobileNumbers.mandiLicenceNo',
        label: 'Mandi Licence',
        width: 6,
        render: (value: string) => (value ? value.toUpperCase() : '-'),
      },
      {
        key: 'keyMobileNumbers.mandiLicenceCopy',
        label: 'Copy of Mandi Licence',
        width: 6,
        render: (value: File) => (value ? value.name : '-'),
      },
      {
        key: 'keyMobileNumbers.regiNo',
        label: 'Registration Number of Shops & Est. Cert.',
        width: 6,
        render: (value: string) => (value ? value.toUpperCase() : '-'),
      },
      {
        key: 'keyMobileNumbers.regiCopy',
        label: 'Copy of Est. Cert.',
        width: 6,
        render: (value: File) => (value ? value.name : '-'),
      },
      {
        key: 'keyMobileNumbers.electricityBill',
        label: 'Electricity Bill (recent) available?',
        width: 4,
        render: (value: string) => (value ? (value === 'true' ? 'Yes' : 'No') : 'No'),
      },
      {
        key: 'keyMobileNumbers.consumenrNo',
        label: 'Consumer Number',
        width: 4,
        render: (value: string) => (value ? value.toUpperCase() : '-'),
      },
      {
        key: 'keyMobileNumbers.electricityBillCopy',
        label: 'Copy of Electricity Bill (recent)',
        width: 4,
        render: (value: File) => (value ? value.name : '-'),
      },
      {
        key: 'keyMobileNumbers.notElectricityBillReason',
        label: 'Reason to not attach electricity bill',
        width: 12,
        render: (value: string) => (value ? convertInTitleCase(value) : '-'),
      },
      {
        key: 'keyMobileNumbers.customerBlacklisted',
        label: 'Whether Customer was blacklisted by any company or authority?',
        render: (value: string) => (value ? (value === 'true' ? 'Yes' : 'No') : 'No'),
      },
      {
        key: 'keyMobileNumbers.blackListedBy',
        label: 'Blacklisted By',
        render: (value: string) => (value ? convertInTitleCase(value) : '-'),
      },
      {
        key: 'keyMobileNumbers.ifBlacklistedReason',
        label: 'Reason of blacklisting',
        render: (value: string) => (value ? convertInTitleCase(value) : '-'),
      },
      {
        key: 'keyMobileNumbers.visitingCard',
        label: 'Visiting Card Collected?',
        render: (value: string) => (value ? (value === 'true' ? 'Yes' : 'No') : 'No'),
      },
      {
        key: 'keyMobileNumbers.visitinContactNo',
        label: 'Contact Number',
        render: (value: string) => (value ? value.toUpperCase() : '-'),
      },
      {
        key: 'keyMobileNumbers.visitingCardCopy',
        label: 'Copy of Visiting Card',
        render: (value: File) => (value ? value.name : '-'),
      },
      {
        key: 'keyMobileNumbers.notVisitingCardReason',
        label: 'Reason for not attaching visiting card',
        render: (value: string) => (value ? convertInTitleCase(value) : '-'),
      },
    ],
  },
  {
    title: 'References',
    sectionType: 'object',
    layout: 'grid',
    gridColumns: 3,
    fields: [
      {
        key: '',
        label: 'Reference 1',
        isHeader: true,
        width: 12,
      },
      {
        key: 'keyMobileNumbers.ref1FName',
        label: 'First Name',
        render: (value: string) => (value ? convertInTitleCase(value || '') : '-'),
      },
      {
        key: 'keyMobileNumbers.ref1MName',
        label: 'Middle Name',
        render: (value: string) => (value ? convertInTitleCase(value || '') : '-'),
      },
      {
        key: 'keyMobileNumbers.ref1LName',
        label: 'Last Name',
        render: (value: string) => (value ? convertInTitleCase(value || '') : '-'),
      },
      {
        key: 'keyMobileNumbers.ref1ContactNo',
        label: 'Contact Number',
        width: 6,
        render: (value: string) => (value ? value : '-'),
      },
      {
        key: 'keyMobileNumbers.ref1Email',
        label: 'Email',
        width: 6,
        render: (value: string) => (value ? value : '-'),
      },
      {
        key: 'keyMobileNumbers.ref1Address',
        label: 'Address',
        width: 12,
        render: (value: Address) => (value ? formatAddress(value) : '-'),
      },
      {
        key: '',
        label: 'Reference 2',
        isHeader: true,
        width: 12,
      },
      {
        key: 'keyMobileNumbers.ref2FName',
        label: 'First Name',
        render: (value: string) => (value ? convertInTitleCase(value || '') : '-'),
      },
      {
        key: 'keyMobileNumbers.ref2MName',
        label: 'Middle Name',
        render: (value: string) => (value ? convertInTitleCase(value || '') : '-'),
      },
      {
        key: 'keyMobileNumbers.ref2LName',
        label: 'Last Name',
        render: (value: string) => (value ? convertInTitleCase(value || '') : '-'),
      },
      {
        key: 'keyMobileNumbers.ref2ContactNo',
        label: 'Contact Number',
        width: 6,
        render: (value: string) => (value ? value : '-'),
      },
      {
        key: 'keyMobileNumbers.ref2Email',
        label: 'Email',
        width: 6,
        render: (value: string) => (value ? value : '-'),
      },
      {
        key: 'keyMobileNumbers.ref2Address',
        label: 'Address',
        width: 12,
        render: (value: Address) => (value ? formatAddress(value) : '-'),
      },
    ],
  },
  {
    title: 'Billing Details',
    sectionType: 'object',
    layout: 'grid',
    gridColumns: 3,
    fields: [
      {
        key: 'billingDetails.billingName',
        label: 'Billing Name/ Regd. Name',
        width: 6,
        render: (value: string) => (value ? convertInTitleCase(value || '') : '-'),
      },
      {
        key: 'billingDetails.commonlyKnownAs',
        label: 'Commonly Known As',
        width: 6,
        render: (value: string) => (value ? convertInTitleCase(value || '') : '-'),
      },
       {
        key: '',
        label: 'Contact Person Details',
        isHeader: true,
        width: 12,
      },
      {
        key: 'billingDetails.contactPersonFName',
        label: 'First Name',
        render: (value: string) => (value ? convertInTitleCase(value || '') : '-'),
      },
      {
        key: 'billingDetails.contactPersonMName',
        label: 'Middle Name',
        render: (value: string) => (value ? convertInTitleCase(value || '') : '-'),
      },
      {
        key: 'billingDetails.contactPersonLName',
        label: 'Last Name',
        render: (value: string) => (value ? convertInTitleCase(value || '') : '-'),
      },
      {
        key: 'billingDetails.primaryContactNo',
        label: 'Primary Contact Number',
        width: 3,
        render: (value: string) => (value ? value : '-'),
      },
      {
        key: 'billingDetails.emailPrimary',
        label: 'Primary Email',
        width: 3,
        render: (value: string) => (value ? value : '-'),
      },
      {
        key: 'billingDetails.secondaryContactNo',
        label: 'Alternate Contact Number',
        width: 3,
        render: (value: string) => (value ? value : '-'),
      },
      {
        key: 'billingDetails.emailSecondary',
        label: 'Alternate Email',
        width: 3,
        render: (value: string) => (value ? value : '-'),
      },
      {
        key: 'billingDetails.billingAddress',
        label: 'Address',
        width: 12,
        render: (value: Address) => (value ? formatAddress(value) : '-'),
      },
      {
        key: 'billingDetails.billingAddressProofCopy',
        label: 'Billing Address Proof Copy',
        width: 6,
        render: (value: File) => (value ? value.name : '-'),
      },
      {
        key: 'billingDetails.billingFormatCopy',
        label: 'Billing Format',
        width: 6,
        render: (value: File) => (value ? value.name : '-'),
      },
    ],
  },
  {
    title: 'Delivery Details',
    sectionType: 'object',
    layout: 'grid',
    gridColumns: 3,
    fields: [
      {
        key: 'deliveryDetails.deliveryAddress',
        label: 'Delivery Address',
        width: 12,
        render: (value: Address) => (value ? formatAddress(value) : '-'),
      },
       {
        key: '',
        label: `Receiving Person's Details`,
        isHeader: true,
        width: 12,
      },
      {
        key: 'deliveryDetails.receivingPersonFName',
        label: 'First Name',
        render: (value: string) => (value ? convertInTitleCase(value || '') : '-'),
      },
      {
        key: 'deliveryDetails.receivingPersonMName',
        label: 'Middle Name',
        render: (value: string) => (value ? convertInTitleCase(value || '') : '-'),
      },
      {
        key: 'deliveryDetails.receivingPersonLName',
        label: 'Last Name',
        render: (value: string) => (value ? convertInTitleCase(value || '') : '-'),
      },
      {
        key: 'deliveryDetails.primaryContactNo',
        label: 'Primary Contact Number',
        width: 3,
        render: (value: string) => (value ? value : '-'),
      },
      {
        key: 'deliveryDetails.emailPrimary',
        label: 'Primary Email',
        width: 3,
        render: (value: string) => (value ? value : '-'),
      },
      {
        key: 'deliveryDetails.secondaryContactNo',
        label: 'Alternate Contact Number',
        width: 3,
        render: (value: string) => (value ? value : '-'),
      },
      {
        key: 'deliveryDetails.emailSecondary',
        label: 'Alternate Email',
        width: 3,
        render: (value: string) => (value ? value : '-'),
      },
      {
        key: 'deliveryDetails.deliveryTime',
        label: 'Delivery Time',
        width: 6,
        render: (value: string) => (value ? value : '-'),
      },
      {
        key: 'deliveryDetails.deliveryAddressProofCopy',
        label: 'Copy of proof of delivery address',
        width: 6,
        render: (value: File) => (value ? value.name : '-'),
      },
    ],
  },
  {
    title: 'Statutory Details',
    sectionType: 'object',
    layout: 'grid',
    gridColumns: 3,
    fields: [
      {
        key: 'statutoryDetails.panNo',
        label: 'PAN Card Number',
        width: 3,
        render: (value: string) => (value ? value.toUpperCase() : ''),
      },
      {
        key: 'statutoryDetails.panCopy',
        label: 'Attached PAN card copy',
        width: 3,
        render: (value: File) => (value ? value.name : ''),
      },
      {
        key: 'statutoryDetails.aadharNo',
        label: 'Aadhar Card Number',
        width: 3,
        render: (value: string) => (value ? value.toUpperCase() : ''),
      },
      {
        key: 'statutoryDetails.aadharCopy',
        label: 'Attached Aadhar card copy',
        width: 3,
        render: (value: File) => (value ? value.name : ''),
      },
      {
        key: 'statutoryDetails.gstn',
        label: 'GST Registration Number',
        render: (value: string) => (value ? value.toUpperCase() : ''),
      },
      {
        key: 'statutoryDetails.regiCertificateCopy',
        label: 'Copy of Registration certificate',
        render: (value: File) => (value ? value.name : ''),
      },
      {
        key: 'statutoryDetails.cinNo',
        label: 'CIN Number',
        render: (value: string) => (value ? value : ''),
      },
      {
        key: 'statutoryDetails.incorpoCertificateCopy',
        label: 'Copy of incorporation certificate duly signed by the director if it is a corporate client',
        width: 12,
        render: (value: File) => (value ? value.name : ''),
      },
      {
        key: 'statutoryDetails.billBookCopy',
        label: 'Copy of Bill Book or Bilty attached',
        width: 12,
        render: (value: File) => (value ? value.name : ''),
      },
      {
        key: 'statutoryDetails.certificationsDetails',
        label: 'Details of certifications',
        width: 3,
        render: (value: string) => (value ? convertInTitleCase(value) : '-'),
      },
      {
        key: 'statutoryDetails.otherCertifications',
        label: 'Any other certifications',
        width: 9,
        render: (value: string) => (value ? value : ''),
      },
      {
        key: 'statutoryDetails.corpRegiDetails',
        label: 'Corporate Registration details',
        width: 3,
        render: (value: string) => (value ? convertInTitleCase(value) : '-'),
      },
      {
        key: 'statutoryDetails.otherCorpRegiDetails',
        label: 'Details of other registrations',
        width: 9,
        render: (value: string) => (value ? value : ''),
      },
    ],
  },
  {
    title: 'Bank Details',
    sectionType: 'object',
    layout: 'grid',
    gridColumns: 3,
    fields: [
       {
        key: '',
        label: 'Bank Account Holder Name',
        isHeader: true,
        width: 12,
      },
      {
        key: 'bankDetails.bankAccHolderFName',
        label: 'First Name',
        render: (value: string) => (value ? convertInTitleCase(value || '') : '-'),
      },
      {
        key: 'bankDetails.bankAccHolderMName',
        label: 'Middle Name',
        render: (value: string) => (value ? convertInTitleCase(value || '') : '-'),
      },
      {
        key: 'bankDetails.bankAccHolderLName',
        label: 'Last Name',
        render: (value: string) => (value ? convertInTitleCase(value || '') : '-'),
      },
      {
        key: 'bankDetails.bankName',
        label: 'Bank Name',
        render: (value: string) => (value ? convertInTitleCase(value || '') : '-'),
      },
      {
        key: 'bankDetails.bankBranch',
        label: 'Bank Name',
        render: (value: string) => (value ? convertInTitleCase(value || '') : '-'),
      },
      {
        key: 'bankDetails.ifscCode',
        label: 'IFSC Code',
        render: (value: string) => (value ? value.toUpperCase() : '-'),
      },
      {
        key: 'bankDetails.bankAccNo',
        label: 'Account Number',
        render: (value: string) => (value ? value : '-'),
      },
      {
        key: 'bankDetails.accType',
        label: 'Type of Account',
        render: (value: string) => (value ? convertInTitleCase(value || '') : '-'),
      },
      {
        key: 'bankDetails.otherAccType',
        label: 'Any Other Account Type',
        render: (value: string) => (value ? convertInTitleCase(value || '') : '-'),
      },
      {
        key: 'bankDetails.bankAddress',
        label: 'Address of Bank & Branch',
        width: 12,
        render: (value: Address) => (value ? formatAddress(value) : '-'),
      },
      {
        key: 'bankDetails.bankStatementCopy',
        label: 'Copy of Bank Statement',
        render: (value: File) => (value ? value.name : ''),
      },
      {
        key: 'bankDetails.ifCancelledCheque',
        label: 'Cancel Cheque available?',
        render: (value: string) => (value ? (value === 'true' ? 'Yes' : 'No') : 'No'),
      },
      {
        key: 'bankDetails.cancelledChequeCopy',
        label: 'Copy of cancelled cheque',
        render: (value: File) => (value ? value.name : ''),
      },
      {
        key: 'bankDetails.notCancelledChequeReason',
        label: 'If cancelled cheque not attached please specify reason',
        width: 12,
        render: (value: string) => (value ? value : '-'),
      },
    ],
  },
  {
    sectionType: 'array',
    layout: 'grid',
    gridColumns: 3,
    fieldArrayName: 'productSpecification',
    title: 'Product Specifications',
    fields: [
      { key: 'articleName', label: 'Article Name', width: 4 },
      { key: 'specifications', label: 'Specifications', width: 4 },
      { key: 'parameters', label: 'Parameters', width: 4 },
      { key: 'packingMaterialSpec', label: 'Pruning Date', width: 6 },
      { key: 'rejectionCriteria', label: 'Harvest Date', width: 6 },
      { key: 'comment', label: 'Expected Quantity', width: 12 },
    ],
  },
  {
    title: 'Payment Terms',
    sectionType: 'object',
    layout: 'grid',
    gridColumns: 3,
    fields: [
      {
        key: 'paymentTerms.paymentMade',
        label: 'Payment To Be Made',
        width: 3,
        render: (value: string) => (value ? convertInTitleCase(value || '') : '-'),
      },
      {
        key: 'paymentTerms.otherPaymentMade',
        label: 'Any Other',
        width: 3,
        render: (value: string) => (value ? convertInTitleCase(value || '') : '-'),
      },
      {
        key: 'paymentTerms.paymentMode',
        label: 'Payment Mode',
        width: 3,
        render: (value: string) => (value ? convertInTitleCase(value || '') : '-'),
      },
      {
        key: 'paymentTerms.otherPaymentMode',
        label: 'Any Other',
        width: 3,
        render: (value: string) => (value ? convertInTitleCase(value || '') : '-'),
      },
      {
        key: 'paymentTerms.marginDeposit',
        label: 'Margin / Deposit Mutually Agreed',
        width: 4,
        render: (value: string) => (value ? value : '-'),
      },
      {
        key: 'bankDetails.rtv',
        label: 'RTV',
        width: 4,
        render: (value: string) => (value ? (value === 'true' ? 'Yes' : 'No') : 'No'),
      },
      {
        key: 'bankDetails.agreementExecuted',
        label: 'Agreement Executed',
        width: 4,
        render: (value: string) => (value ? (value === 'true' ? 'Yes' : 'No') : 'No'),
      },
       {
        key: '',
        label: 'Security Deposit Details',
        isHeader: true,
        width: 12,
      },
      {
        key: 'paymentTerms.securityDepoCheqNo',
        label: 'Cheque Number',
        width: 3,
        render: (value: string) => (value ? value.toUpperCase() : '-'),
      },
      {
        key: 'paymentTerms.securityDepoAmt',
        label: 'Amount',
        width: 3,
        render: (value: string) => (value ? `${value} Rs` : '-'),
      },
      {
        key: 'paymentTerms.lc',
        label: 'L/C',
        width: 3,
        render: (value: File) => (value ? value.name : ''),
      },
      {
        key: 'paymentTerms.bg',
        label: 'B/G',
        width: 3,
        render: (value: File) => (value ? value.name : ''),
      },
      {
        key: '',
        label: 'Initial Exposure Limit',
        isHeader: true,
        width: 12,
      },
      {
        key: 'paymentTerms.IELinAmt',
        label: 'In Amount',
        width: 4,
        render: (value: string) => (value ? `${value} Rs` : '-'),
      },
      {
        key: 'paymentTerms.IELRecommendedBy',
        label: 'Recommended By',
        width: 4,
        render: (value: string) => (value ? convertInTitleCase(value || '') : '-'),
      },
      {
        key: 'paymentTerms.IELRecommendedDate',
        label: 'Recommended Date',
        width: 4,
        render: (value: string) => (value ? formatDate(value || '') : '-'),
      },
       {
        key: '',
        label: 'Revision of Exposure Limit',
        isHeader: true,
        width: 12,
      },
      {
        key: 'paymentTerms.RELinAmt',
        label: 'In Amount',
        width: 4,
        render: (value: string) => (value ? `${value} Rs` : '-'),
      },
      {
        key: 'paymentTerms.RELRecommendedBy',
        label: 'Recommended By',
        width: 4,
        render: (value: string) => (value ? convertInTitleCase(value || '') : '-'),
      },
      {
        key: 'paymentTerms.RELRecommendedDate',
        label: 'Recommended Date',
        width: 4,
        render: (value: string) => (value ? formatDate(value || '') : '-'),
      },
      {
        key: 'paymentTerms.docEvidenceCopy',
        label: 'Documentary Evidence',
        width: 4,
        render: (value: File) => (value ? value.name : ''),
      },
      {
        key: 'paymentTerms.reason',
        label: 'Reason',
        width: 8,
        render: (value: string) => (value ? value : '-'),
      },
    ],
  },
  {
    title: 'Office Use Only',
    sectionType: 'object',
    layout: 'grid',
    gridColumns: 3,
    fields: [
      {
        key: 'officeUseOnly.proposerBDName',
        label: 'Proposer / BD Name',
        width: 4,
        render: (value: string) => (value ? convertInTitleCase(value || '') : '-'),
      },
      {
        key: 'officeUseOnly.recommendedBy',
        label: 'Recommended By',
        width: 4,
        render: (value: string) => (value ? convertInTitleCase(value || '') : '-'),
      },
      {
        key: 'officeUseOnly.approvedBy',
        label: 'Approved By',
        width: 4,
        render: (value: string) => (value ? convertInTitleCase(value || '') : '-'),
      },
      {
        key: 'officeUseOnly.pflCoordinator',
        label: 'PFL Co-ordinator',
        width: 4,
        render: (value: string) => (value ? convertInTitleCase(value || '') : '-'),
      },
      {
        key: 'officeUseOnly.dispatchLocationPfl',
        label: 'Dispatch Location - PFL',
        width: 4,
        render: (value: string) => (value ? convertInTitleCase(value || '') : '-'),
      },
      {
        key: 'officeUseOnly.relationshipManager',
        label: 'Relationship Manager',
        width: 4,
        render: (value: string) => (value ? convertInTitleCase(value || '') : '-'),
      },
      {
        key: 'officeUseOnly.avgBillingMonthly',
        label: 'Expected Average Monthly Billing',
        width: 6,
        render: (value: string) => (value ? value : '-'),
      },
      {
        key: 'officeUseOnly.volumeMonthly',
        label: 'Volume In Tonnes Per Month',
        width: 6,
        render: (value: string) => (value ? value : '-'),
      },
      {
        key: 'officeUseOnly.customerVerification',
        label: 'Customer Verification Completed ?',
        width: 3,
        render: (value: string) => (value ? (value === 'true' ? 'Yes' : 'No') : 'No'),
      },
      {
        key: 'officeUseOnly.verificationAgency',
        label: 'Verification Agency Name',
        width: 3,
        render: (value: string) => (value ? convertInTitleCase(value || '') : '-'),
      },
      {
        key: 'officeUseOnly.validityPeriod',
        label: 'Validity Period',
        width: 3,
        render: (value: string) => (value ? formatDate(value || '') : '-'),
      },
      {
        key: 'officeUseOnly.dueDiligenceDone',
        label: 'Due Diligence Done?',
        width: 3,
        render: (value: string) => (value ? (value === 'true' ? 'Yes' : 'No') : 'No'),
      },
      {
        key: 'officeUseOnly.creditWorthinessDue',
        label: 'Renewal of Credit Worthiness Due',
        width: 4,
        render: (value: string) => (value ? convertInTitleCase(value || '') : '-'),
      },
      {
        key: 'officeUseOnly.keyAccountPersonAssigned',
        label: 'Key Account Person Assigned',
        width: 4,
        render: (value: string) => (value ? convertInTitleCase(value || '') : '-'),
      },
      {
        key: 'officeUseOnly.sinceWhen',
        label: 'Since When',
        width: 4,
        render: (value: string) => (value ? formatDate(value || '') : '-'),
      },
      {
        key: 'officeUseOnly.ledgerCreatedDate',
        label: 'Ledger Created Date',
        width: 4,
        render: (value: string) => (value ? formatDate(value || '') : '-'),
      },
      {
        key: 'officeUseOnly.ledgerCreatedBy',
        label: 'Ledger Created By',
        width: 4,
        render: (value: string) => (value ? convertInTitleCase(value || '') : '-'),
      },
      {
        key: 'officeUseOnly.ledgerVerifiedApprovedBy',
        label: 'Ledger verified & Approved By',
        width: 4,
        render: (value: string) => (value ? convertInTitleCase(value || '') : '-'),
      },
      {
        key: 'officeUseOnly.additionalNotes',
        label: 'Any other description & brief of the customer requirement',
        width: 12,
        render: (value: string) => (value ? convertInTitleCase(value || '') : '-'),
      },
    ],
  },
];
