import { GridRenderCellParams } from '@mui/x-data-grid';
import { Chip } from '@mui/material';
import { CustomGridColDef } from '@prime-fresh/ui_shared';
import { convertInTitleCase, getDocStatusColor } from '@prime-fresh/shared/modules';

export const lpVoucherColumns: CustomGridColDef[] = [
  {
    field: 'overAllStatus',
    headerName: 'Status',
    flex: 1,
    minWidth: 130,
    align: 'center',
    headerAlign: 'center',
    hide: false,
    isMobileVisible: true,
    renderCell: (params: GridRenderCellParams) => {
      const status = convertInTitleCase(params.row.overAllStatus || '');
      return (
        <Chip
          label={status}
          size="small"
          sx={{
            flex: 1,
            minWidth: 80,
            color: '#FFF',
            backgroundColor: getDocStatusColor(params.row.overAllStatus || ''),
          }}
        />
      );
    },
  },
  {
    field: 'voucherNo',
    headerName: 'Voucher Number',
    flex: 1,
    minWidth: 130,
    align: 'center',
    headerAlign: 'center',
    hide: false,
    isMobileVisible: true,
    valueGetter: (value: string) => (value ? convertInTitleCase(value) : ''),
  },
  {
    field: 'createdBy',
    headerName: 'Created By',
    flex: 1,
    minWidth: 120,
    align: 'center',
    headerAlign: 'center',
    hide: false,
    valueGetter: (value: string) => (value ? convertInTitleCase(value) : ''),
  },
  {
    field: 'createdDate',
    headerName: 'Created Date',
    flex: 1,
    minWidth: 120,
    align: 'center',
    headerAlign: 'center',
    hide: false,
  },
  {
    field: 'createdTime',
    headerName: 'Created Time',
    flex: 1,
    minWidth: 120,
    align: 'center',
    headerAlign: 'center',
    hide: false,
  },
  {
    field: 'grnNo',
    headerName: 'GRN Number',
    flex: 1,
    minWidth: 130,
    align: 'center',
    headerAlign: 'center',
    hide: true,
    valueGetter: (value: string) => (value ? value.toUpperCase() : ''),
  },
  {
    field: 'companyName',
    headerName: 'Company Name',
    flex: 1,
    minWidth: 200,
    headerAlign: 'center',
    hide: false,
    valueGetter: (value: string) => (value ? convertInTitleCase(value) : ''),
  },
  {
    field: 'debitCreditTo',
    headerName: 'Debit From / Credit To',
    flex: 1,
    minWidth: 150,
    headerAlign: 'center',
    hide: false,
    valueGetter: (value: string) => (value ? convertInTitleCase(value) : ''),
  },
  {
    field: 'payReceivedFrom',
    headerName: 'Received From / Pay To',
    flex: 1,
    minWidth: 150,
    headerAlign: 'center',
    hide: false,
    valueGetter: (value: string) => (value ? convertInTitleCase(value) : ''),
  },
  {
    field: 'location',
    headerName: 'Location',
    flex: 1,
    minWidth: 100,
    align: 'center',
    headerAlign: 'center',
    hide: false,
    valueGetter: (value: string) => (value ? convertInTitleCase(value) : ''),
  },
  {
    field: 'noOfLabours',
    type: 'number',
    headerName: 'No Of Labours',
    flex: 1,
    minWidth: 100,
    align: 'center',
    headerAlign: 'center',
    hide: false,
    valueGetter: (value: number) => (value ? Number(value) : ''),
  },
  {
    field: 'ratePerLabour',
    headerName: 'Rate Per Labours',
    flex: 1,
    minWidth: 100,
    align: 'center',
    headerAlign: 'center',
    hide: true,
    valueGetter: (value: number) => (value ? `${Number(value)} Rs` : ''),
  },
  {
    field: 'loadingDate',
    headerName: 'Loading Date',
    flex: 1,
    minWidth: 100,
    align: 'center',
    headerAlign: 'center',
    hide: false,
    valueGetter: (value: string) => (value ? value : ''),
  },
  {
    field: 'totalAmt',
    headerName: 'Total Amount',
    flex: 1,
    minWidth: 100,
    align: 'center',
    headerAlign: 'center',
    hide: false,
    valueGetter: (value: number) => (value ? `${Number(value)} Rs` : ''),
  },
  {
    field: 'amtWords',
    headerName: 'Amount in Words',
    flex: 1,
    minWidth: 200,
    headerAlign: 'center',
    hide: true,
    valueGetter: (value: string) => (value ? convertInTitleCase(value) : ''),
  },
  {
    field: 'paymentMode',
    headerName: 'Payment Mode',
    flex: 1,
    minWidth: 100,
    align: 'center',
    headerAlign: 'center',
    hide: true,
    valueGetter: (value: string) => (value ? convertInTitleCase(value) : ''),
  },
  {
    field: 'contactNo',
    headerName: 'Contact No',
    flex: 1,
    minWidth: 100,
    align: 'center',
    headerAlign: 'center',
    hide: true,
    valueGetter: (value: string) => (value ? value : ''),
  },
  {
    field: 'altContactNo',
    headerName: 'Alt. Contact No',
    flex: 1,
    minWidth: 100,
    align: 'center',
    headerAlign: 'center',
    hide: true,
    valueGetter: (value: string) => (value ? value : ''),
  },
  {
    field: 'receiverName',
    headerName: 'Receiver Name',
    flex: 1,
    minWidth: 150,
    align: 'center',
    headerAlign: 'center',
    hide: true,
    valueGetter: (value: string) => (value ? convertInTitleCase(value) : ''),
  },
  {
    field: 'kyc',
    headerName: 'KYC',
    flex: 1,
    minWidth: 100,
    align: 'center',
    headerAlign: 'center',
    hide: true,
    valueGetter: (value: boolean) => (value === true ? 'Yes' : 'No'),
  },
  {
    field: 'remark',
    headerName: 'Remark',
    flex: 1,
    minWidth: 200,
    headerAlign: 'center',
    hide: true,
    valueGetter: (value: string) => (value ? convertInTitleCase(value) : ''),
  },
];
