import { CustomerTypes, CustomerCategory, KeyMobileNumbers, BillingDetails, DeliveryDetails, StatutoryDetails, BankDetails, ProductSpecification, PaymentTerms, OfficeUseOnly } from '../models';
import { initValAddress } from './initValAddress';

const initCustomerTypes: CustomerTypes = {
    id: '',
    name: '',
};

const initCustomerCategory: CustomerCategory = {
    id: '',
    name: '',
};

const initKeyMobileNumbers: KeyMobileNumbers = {
    accDeptFName: '',
    accDeptMName: '',
    accDeptLName: '',
    accDeptMobileNo: '',
    ownerFName: '',
    ownerMName: '',
    ownerLName: '',
    ownerMobileNo: '',
    mandiLicenceNo: '',
    mandiLicenceCopy: '',
    regiNo: '',
    regiCopy: '',
    electricityBill: '',
    consumenrNo: '',
    electricityBillCopy: '',
    notElectricityBillReason: '',
    customerBlacklisted: '',
    ifBlacklistedReason: '',
    blackListedBy: '',
    visitingCard: '',
    visitinContactNo: '',
    visitingCardCopy: '',
    notVisitingCardReason: '',
    ref1FName: '',
    ref1MName: '',
    ref1LName: '',
    ref1Address: initValAddress,
    ref1ContactNo: '',
    ref1Email: '',
    ref2FName: '',
    ref2MName: '',
    ref2LName: '',
    ref2Address: initValAddress,
    ref2ContactNo: '',
    ref2Email: '',
};

const initBillingDetails: BillingDetails = {
    billingName: '',
    contactPersonFName: '',
    contactPersonMName: '',
    contactPersonLName: '',
    commonlyKnownAs: '',
    billingAddress: initValAddress,
    billingAddressProofCopy: '',
    primaryContactNo: '',
    secondaryContactNo: '',
    emailPrimary: '',
    emailSecondary: '',
    billingFormatCopy: '',
};

const initDeliveryDetails: DeliveryDetails = {
    deliveryAddress: initValAddress,
    deliveryAddressProofCopy:'',
    deliveryTime: new Date(2023, 11, 25),
    receivingPersonFName: '',
    receivingPersonMName: '',
    receivingPersonLName: '',
    primaryContactNo: '',
    secondaryContactNo: '',
    emailPrimary: '',
    emailSecondary: '',
};

const initStatutoryDetails: StatutoryDetails = {
    panNo: '',
    panCopy: '',
    aadharNo: '',
    addharCopy: '',
    gstn: '',
    regiCertificateCopy: '',
    billBookCopy: '',
    certificationsDetails: '',
    otherCertifications: '',
    corpRegiDetails: '',
    otherCorpRegiDetails: '',
    incorpoCertificateCopy: '',
    cinNo: '',
};

const initBankDetails: BankDetails = {
    ifCancelledCheque: '',
    notCancelledChequeReason: '',
    cancelledChequeCopy: '',
    accType: '',
    otherAccType: '',
    bankStatementCopy: '',
    bankAccHolderFName: '',
    bankAccHolderMName: '',
    bankAccHolderLName: '',
    bankName: '',
    bankBranch: '',
    bankAccNo: '',
    ifscCode: '',
    bankAddress: initValAddress,
};

const initProductSpecification: ProductSpecification[] = [
    {
        articleName: '',
        specifications: '',
        parameters: '',
        packingMaterialSpec: '',
        rejectionCriteria: '',
        comment: '',
    },
];

const initPaymentTerms: PaymentTerms = {
    paymentMade: '',
    otherPaymentMade: '',
    paymentMode: '',
    otherPaymentMode: '',
    marginDeposit: '',
    rtv: '',
    agreementExecuted: '',
    lc: '',
    bg: '',
    securityDepoCheqNo: '',
    securityDepoAmt: 0,
    IELinAmt: 0,
    IELRecommendedBy: '',
    IELRecommendedDate: new Date(2023, 11, 25),
    RELinAmt: 0,
    RELRecommendedBy: '',
    RELRecommendedDate: new Date(2023, 11, 25),
    reason: '',
    docEvidenceCopy: '',
};

const initOfficeUseOnly: OfficeUseOnly = {
    proposerBDName: '',
    pflCoordinator: '',
    recommendedBy: '',
    dispatchLocationPfl: '',
    approvedBy: '',
    relationshipManager: '',
    avgBillingMonthly: 0,
    volumeMonthly: 0,
    customerVerification: '',
    verificationAgency: '',
    validityPeriod: '',
    dueDiligenceDone: '',
    creditWorthinessDue: '',
    keyAccountPersonAssigned: '',
    sinceWhen: '',
    ledgerCreatedDate: new Date(2023, 11, 25),
    ledgerCreatedBy: '',
    ledgerVerifiedApprovedBy: '',
    additionalNotes: '',
    customerCode: '',
    createdBy: '',
    createdDate: new Date(2023, 11, 25),
};

export const initValCustomer = {
    organisationName: '',
    customerTypes: initCustomerTypes,
    customerCategory: initCustomerCategory,
    organisationType: '',
    otherType: '',
    customerAddress: initValAddress,
    primaryContactNo: '',
    secondaryContactNo: '',
    emailPrimary: '',
    emailSecondary: '',
    keyMobileNumbers: initKeyMobileNumbers,
    billingDetails: initBillingDetails,
    deliveryDetails: initDeliveryDetails,
    statutoryDetails: initStatutoryDetails,
    bankDetails: initBankDetails,
    productSpecification: initProductSpecification,
    paymentTerms: initPaymentTerms,
    officeUseOnly: initOfficeUseOnly,
};
