import { IGRN, IGRNProducts } from '@prime-fresh/purchase_api';

export const grnProductsInitialValue: IGRNProducts = {
  productName: null,
  origin: null,
  variety: null,
  count: null,
  size: null,
  uom: null,
  quantity: 0,
  unitPrice: 0,
  amount: null,
  rtv: false,
  purchaseDate: null,
  expectedHarvestDate: null,
  dispatchDate: null,
  deliveryDate: null,
  deliveryLocation: null,
  revisedRate: 0,
  revisedQuantity: 0,
  packingMaterialWeight: 0,
  netWeight: 0,
  grossWeight: 0,
};
export const grnInitialValue: Omit<IGRN, 'id'> = {
  locationType: 'cc',
  grnType: 'purchase',
  purchaseType: 'fixed price sales',
  dealSlipId: null,
  billNo: null,
  companyName: null,
  purchaseInstructionsBy: null,
  purchaseLocation: null,
  otherPurchaseLoc: null,
  purchaseForSalesLocation: null,
  otherPurchaseForSalesLoc: null,
  specialReq: null,
  source: 'vendor',
  selectedParty: null,
  grnProducts: [grnProductsInitialValue],
  subTotalAmt: 0,
  freight: 0,
  otherCharges: 0,
  totalAmt: 0,
  amtWords: null,
  purchasedBy: null,
  deliveryReceivingPerson: null,
  receivedThrough: null,
  vehicleNo: null,
  timeIn: null,
  cratesIn: 0,
  securityPerson: null,
  rmn: null,
  paymentInfo: {
    paymentMode: null,
    advancePaidAmt: null,
    paymentDate: null,
    paymentTerms: null,
    creditPeriod: null,
    dueDate: null,
    remainingAmt: null,
  },
  remark: null,
  billImage: null,
};

export const grnInitValForFilter = {
  companyName: null,
  purchaseLocation: null,
  purchaseForSalesLocation: null,
  locationType: null,
  grnType: null,
  source: null,
}