export const initValPaymentRequest = {
    paymentDate: new Date(),
    partyName: '',
    amount: 0,
    bankAccNo: '',
    ifscCode: '',
    paymentMode: '',
    typesOfTransaction: '',
    vehicleNo: '',
    placeOfPurchase: '',
    contactperson: '',
    costCenter: '',
    kycByEmail: 'no',
    remark:'',
}