import { GRNProducts, PostGRN } from "@prime-fresh/purchase_api";
export const initValGRNProducts: GRNProducts = {
    productName: null,
    count: null,
    size: null,
    uom: null,
    quantity: null,
    unitPrice: null,
    amount: null,
    rtv: false,
    purchaseDate: null,
    expectedHarvestDate: null,
    dispatchDate: null,
    deliveryDate: null,
    deliveryLocation: "",
    revisedRate: 0,
    revisedQuantity: 0,
    packingMaterialWeight: 0,
    netWeight: 0,
    grossWeight: 0,
}

export const initValGRN: PostGRN = {
    locationType: "cc",
    grnType: "purchase",
    purchaseType: "fixed price sales",
    dealSlipId: null,
    billNo: null,
    companyName: null,
    purchaseInstructionsBy: null,
    purchaseLocation: null,
    otherPurchaseLoc: null,
    purchaseForSalesLocation: null,
    otherPurchaseForSalesLoc: null,
    specialReq: null,
    source: 'vendor',
    selectedParty: null,
    grnProducts: [initValGRNProducts],
    deliveryReceivingPerson: null,
    subTotalAmt: 0,
    totalAmt: 0,
    amtWords: null,
    freight: null,
    otherCharges: null,
    purchasedBy: null,
    receivedThrough: null,
    securityPerson: null,
    vehicleNo: null,
    timeIn: null,
    cratesIn: null,
    rmn: null,
    remark: null,
    billImage: null,
}