import { GRNProducts, PostGRN } from "@prime-fresh/purchase_api";
export const initValGRNProducts: GRNProducts = {
    product: '',
    count: '',
    uom: '',
    quantity: 0,
    rate: 0,
    amt: 0,
    rtv: 'no',
    purchaseDate: '',
    expectedHarvestDate: '',
    dispatchDate: '',
    deliveryDate: '',
    deliveryLocation: '',
    revisedRate: 0,
    revisedQuantity: 0,
}

export const initValGRN: PostGRN = {
    grnType: "",
    purchaseType: "fixed price sales",
    dealSlipId: '',
    billNo: '',
    companyName: '',
    purchaseInstructionsBy: '',
    purchaseLocation: '',
    purchaseForSalesLocation: '',
    specialReq: '',
    source: 'vendor',
    selectedParty: '',
    products: [initValGRNProducts],
    deliveryReceivingPerson: '',
    subTotalAmt: 0,
    totalAmt: 0,
    amtWords: '',
    freight: 0,
    otherCharges: 0,
    purchasedBy: '',
    receivedThrough: '',
    securityPerson: '',
    vehicleNo: '',
    timeIn: '',
    cratesIn: 0,
    rmn: '',
    remark: '',
    billImage: null,
}