import { GRNProducts, PostGRN } from "@prime-fresh/purchase_api";
export const initValGRNProducts: GRNProducts = {
    product: null,
    count: null,
    uom: null,
    quantity: 0,
    rate: 0,
    amt: 0,
    rtv: 'no',
    purchaseDate: null,
    expectedHarvestDate: null,
    dispatchDate: null,
    deliveryDate: null,
    deliveryLocation: null,
    revisedRate: 0,
    revisedQuantity: 0,
}

export const initValGRN: PostGRN = {
    grnType: "",
    dealSlipId: null,
    billNo: null,
    serialNo: null,
    companyName: null,
    purchaseRequestByWhom: null,
    purchaseLocation: null,
    purchaseForWhich: null,
    specialReq: null,
    source: 'vendor',
    selectedParty: null,
    products: [initValGRNProducts],
    deliveryReceivingPerson: null,
    subTotalAmt: 0,
    totalAmt: 0,
    amtWords: null,
    freight: 0,
    otherCharges: 0,
    purchasedBy: null,
    receivedThrough: null,
    securityPerson: null,
    vehicleNo: null,
    timeIn: null,
    cratesIn: 0,
    rmn: null,
    remark: null,
    billImage: null,
}