// export type PostSecondSaleProducts = {
//     product: string | null,
//     uom: string | null,
//     qty: number| null,
//     rate: number| null,
//     amount: number| null,
// }
export type PostSecondSaleProducts = {
    productName: string | null,
    count: string | null,
    size: string | null,
    uom: string | null,
    quantity: number | null,
    unitPrice: number | null,
    amount: number | null,
    grossWeight: number | null,
    packingMaterialWeight: number | null,
    netWeight: number | null,
}

export type GetSecondSaleProducts = {
    id: string,
    productName: { id: string, productName: string },
    count: string | null,
    size: string | null,
    uom: { id: string, unit: string },
    quantity: number | null,
    unitPrice: number | null,
    amount: number | null,
    grossWeight: number | null,
    packingMaterialWeight: number | null,
    netWeight: number | null,
}

export type PostSecondSaleRegister = {
    companyName: string | null,
    location: string | null,
    dcNo: string | null,
    saleDate: string | null,
    buyerName: string | null,
    buyerMobNo: string | null,
    reasonForSale: string | null,
    approvedBy: string | null,
    soldBy: string | null,
    secondSaleProducts: PostSecondSaleProducts[],
    totalNetWeight: number | null,
    totalAmt: number | null,
    totalAmtInWords: string | null,
    paidAmount: string | null,
    paymentMode: string | null,
    pendingAmt: string | null,
    remarks: string | null,
    comments: string | null,
    submittedBy: string | null,
    mobileNo: string | null,
}

export type GetSecondSaleRegister = {
    id: string,
    companyName: { id: string, companyName: string },
    location: { id: string, name: string },
    dcNo: { id: string, dcNo: string },
    saleDate: string,
    buyerName: string,
    buyerMobNo: string,
    reasonForSale: string,
    approvedBy: string,
    soldBy: string,
    secondSaleProducts: GetSecondSaleProducts[],
    totalNetWeight: number,
    totalAmt: number,
    totalAmtInWords: string,
    paidAmount: string,
    paymentMode: string,
    pendingAmt: string,
    remarks: string,
    comments: string,
    submittedBy: string,
    mobileNo: string,
}