export type GRNFilterParams = {
    grnNo: string,
    locationType: string,
    grnType: string,
    purchaseType: string,
    companyName: string,
    purchaseInstructionsBy: string,
    dealSlipId: string,
    purchaseLocation: string,
    source: string,
    vendorId: string,
    farmerId: string,
    vendorcategoryId: string,
    vendorsubcategoryId: string,
    productId: string,
    productCategoryId: string,
    productSubCategoryId: string,
    dateFrom: string,
    dateTo: string,
}
export const initValGRNFilterParams: GRNFilterParams = {
        grnNo: "",
        locationType: "",
        grnType: "",
        purchaseType: "",
        companyName: "",
        purchaseInstructionsBy: "",
        dealSlipId: "",
        purchaseLocation: "",
        source: "",
        vendorId: "",
        farmerId: "",
        vendorcategoryId: "",
        vendorsubcategoryId: "",
        productId: "",
        productCategoryId: "",
        productSubCategoryId: "",
        dateFrom: "",
        dateTo: "",
}