export type GRNFilterParams = {
    grnNo: string | null,
    locationType: string | null,
    grnType: string | null,
    purchaseType: string | null,
    companyName: string | null,
    purchaseInstructionsBy: string | null,
    dealSlipId: string | null,
    purchaseLocation: string | null,
    source: string | null,
    vendorId: string | null,
    farmerId: string | null,
    vendorcategoryId: string | null,
    vendorsubcategoryId: string | null,
    productId: string | null,
    productCategoryId: string | null,
    productSubCategoryId: string | null,
    dateFrom: string | null,
    dateTo: string | null,
}