import * as Yup from 'yup';

// const addressSchema = Yup.object().shape({
//     address1: Yup.string().required('Address Line 1 is required'),
//     address2: Yup.string(),
//     location: Yup.string().required('Location is required'),
//     city: Yup.string().required('City is required'),
//     state: Yup.string().required('State is required'),
//     pincode: Yup.string().required('Pincode is required').matches(/^\d{6}$/, 'Pincode must be 6 digits'),
// });

// // const customerTypesSchema = Yup.object().shape({
// //     id: Yup.string().required('Customer Type ID is required'),
// //     name: Yup.string().required('Customer Type Name is required'),
// // });

// // const customerCategorySchema = Yup.object().shape({
// //     id: Yup.string().required('Customer Category ID is required'),
// //     name: Yup.string().required('Customer Category Name is required'),
// // });

// const keyMobileNumbersSchema = Yup.object().shape({
//     accDeptFName: Yup.string().required('Account Department First Name is required'),
//     accDeptMName: Yup.string(),
//     accDeptLName: Yup.string().required('Account Department Last Name is required'),
//     accDeptMobileNo: Yup.string().required('Account Department Mobile No. is required').matches(/^\d{10}$/, 'Mobile number must be 10 digits'),
//     ownerFName: Yup.string().required('Owner First Name is required'),
//     ownerMName: Yup.string(),
//     ownerLName: Yup.string().required('Owner Last Name is required'),
//     ownerMobileNo: Yup.string().required('Owner Mobile No. is required').matches(/^\d{10}$/, 'Mobile number must be 10 digits'),
//     mandiLicenceNo: Yup.string().required('Mandi License No. is required'),
//     mandiLicenceCopy: Yup.string(),
//     regiNo: Yup.string().required('Registration No. is required'),
//     regiCopy: Yup.string(),
//     electricityBill: Yup.boolean().required(),
//     consumenrNo: Yup.string().required('Consumer No. is required if electricity bill is provided'),
//     electricityBillCopy: Yup.string(),
//     notElectricityBillReason: Yup.string().required('Reason is required if no electricity bill is provided'),
//     customerBlacklisted: Yup.boolean().required(),
//     ifBlacklistedReason: Yup.string().required('Reason for blacklisting is required'),
//     blackListedBy: Yup.string(),
//     visitingCard: Yup.boolean().required(),
//     visitinContactNo: Yup.string(),
//     visitingCardCopy: Yup.string(),
//     notVisitingCardReason: Yup.string(),
//     ref1FName: Yup.string().required('Reference 1 First Name is required'),
//     ref1MName: Yup.string(),
//     ref1LName: Yup.string().required('Reference 1 Last Name is required'),
//     ref1Address: addressSchema.required('Reference 1 Address is required'),
//     ref1ContactNo: Yup.string().required('Reference 1 Contact No. is required').matches(/^\d{10}$/, 'Contact number must be 10 digits'),
//     ref1Email: Yup.string().email('Invalid email format').required('Reference 1 Email is required'),
//     ref2FName: Yup.string(),
//     ref2MName: Yup.string(),
//     ref2LName: Yup.string(),
//     ref2Address: addressSchema,
//     ref2ContactNo: Yup.string().matches(/^\d{10}$/, 'Contact number must be 10 digits'),
//     ref2Email: Yup.string().email('Invalid email format'),
// });

// const billingDetailsSchema = Yup.object().shape({
//     billingName: Yup.string().required('Billing Name is required'),
//     contactPersonFName: Yup.string().required('Contact Person First Name is required'),
//     contactPersonMName: Yup.string(),
//     contactPersonLName: Yup.string().required('Contact Person Last Name is required'),
//     commonlyKnownAs: Yup.string(),
//     billingAddress: addressSchema.required('Billing Address is required'),
//     billingAddressProofCopy: Yup.string(),
//     primaryContactNo: Yup.string().required('Primary Contact No. is required').matches(/^\d{10}$/, 'Contact number must be 10 digits'),
//     secondaryContactNo: Yup.string().matches(/^\d{10}$/, 'Contact number must be 10 digits'),
//     emailPrimary: Yup.string().email('Invalid email format').required('Primary Email is required'),
//     emailSecondary: Yup.string().email('Invalid email format'),
//     billingFormatCopy: Yup.string(),
// });

// const deliveryDetailsSchema = Yup.object().shape({
//     deliveryAddress: addressSchema.required('Delivery Address is required'),
//     deliveryAddressProofCopy: Yup.string().nullable(),
//     deliveryTime: Yup.string().required('Delivery Time is required'),
//     receivingPersonFName: Yup.string().required('Receiving Person First Name is required'),
//     receivingPersonMName: Yup.string(),
//     receivingPersonLName: Yup.string().required('Receiving Person Last Name is required'),
//     primaryContactNo: Yup.string().required('Primary Contact No. is required').matches(/^\d{10}$/, 'Contact number must be 10 digits'),
//     secondaryContactNo: Yup.string().matches(/^\d{10}$/, 'Contact number must be 10 digits'),
//     emailPrimary: Yup.string().email('Invalid email format').required('Primary Email is required'),
//     emailSecondary: Yup.string().email('Invalid email format'),
// });

// const statutoryDetailsSchema = Yup.object().shape({
//     panNo: Yup.string().required('PAN No. is required'),
//     panCopy: Yup.string(),
//     aadharNo: Yup.string().required('Aadhar No. is required').matches(/^\d{12}$/, 'Aadhar number must be 12 digits'),
//     addharCopy: Yup.string(),
//     gstn: Yup.string().required('GSTN is required'),
//     regiCertificateCopy: Yup.string(),
//     billBookCopy: Yup.string(),
//     certificationsDetails: Yup.string(),
//     otherCertifications: Yup.string(),
//     corpRegiDetails: Yup.string(),
//     otherCorpRegiDetails: Yup.string(),
//     incorpoCertificateCopy: Yup.string(),
//     cinNo: Yup.string().required('CIN No. is required'),
// });

// const bankDetailsSchema = Yup.object().shape({
//     ifCancelledCheque: Yup.boolean().required(),
//     notCancelledChequeReason: Yup.string().required('Reason is required if no cancelled cheque is provided'),
//     cancelledChequeCopy: Yup.string(),
//     accType: Yup.string().required('Account Type is required'),
//     otherAccType: Yup.string(),
//     bankStatementCopy: Yup.string(),
//     bankAccHolderFName: Yup.string().required('Bank Account Holder First Name is required'),
//     bankAccHolderMName: Yup.string(),
//     bankAccHolderLName: Yup.string().required('Bank Account Holder Last Name is required'),
//     bankName: Yup.string().required('Bank Name is required'),
//     bankBranch: Yup.string().required('Bank Branch is required'),
//     bankAccNo: Yup.string().required('Bank Account No. is required'),
//     ifscCode: Yup.string().required('IFSC Code is required'),
//     bankAddress: addressSchema.required('Bank Address is required'),
// });

// const productSpecificationSchema = Yup.object().shape({
//     articleName: Yup.string().required('Article Name is required'),
//     specifications: Yup.string().required('Specifications are required'),
//     parameters: Yup.string().required('Parameters are required'),
//     packingMaterialSpec: Yup.string().required('Packing Material Specification is required'),
//     rejectionCriteria: Yup.string().required('Rejection Criteria are required'),
//     comment: Yup.string(),
// });

// const paymentTermsSchema = Yup.object().shape({
//     paymentMade: Yup.string().required('Payment Made is required'),
//     otherPaymentMade: Yup.string(),
//     paymentMode: Yup.string().required('Payment Mode is required'),
//     otherPaymentMode: Yup.string(),
//     marginDeposit: Yup.string().required('Margin Deposit is required'),
//     rtv: Yup.boolean().required(),
//     agreementExecuted: Yup.boolean().required(),
//     lc: Yup.string(),
//     bg: Yup.string(),
//     securityDepoCheqNo: Yup.string(),
//     securityDepoAmt: Yup.number().required('Security Deposit Amount is required'),
//     IELinAmt: Yup.number().required('Initial Exposure Limit (IEL) Amount is required'),
//     IELRecommendedBy: Yup.string(),
//     IELRecommendedDate: Yup.string(),
//     RELinAmt: Yup.number(),
//     RELRecommendedBy: Yup.string(),
//     RELRecommendedDate: Yup.string(),
//     reason: Yup.string(),
//     docEvidenceCopy: Yup.string(),
// });

// const officeUseOnlySchema = Yup.object().shape({
//     proposerBDName: Yup.string(),
//     pflCoordinator: Yup.string(),
//     recommendedBy: Yup.string(),
//     dispatchLocationPfl: Yup.string(),
//     approvedBy: Yup.string(),
//     relationshipManager: Yup.string(),
//     avgBillingMonthly: Yup.number(),
//     volumeMonthly: Yup.number(),
//     customerVerification: Yup.boolean(),
//     verificationAgency: Yup.string(),
//     validityPeriod: Yup.string(),
//     dueDiligenceDone: Yup.boolean(),
//     creditWorthinessDue: Yup.string(),
//     keyAccountPersonAssigned: Yup.string(),
//     sinceWhen: Yup.string(),
//     ledgerCreatedDate: Yup.string(),
//     ledgerCreatedBy: Yup.string(),
//     ledgerVerifiedApprovedBy: Yup.string(),
//     additionalNotes: Yup.string(),
//     customerCode: Yup.string(),
//     createdBy: Yup.string(),
//     createdDate: Yup.string(),
// });

export const customerValidationSchema = Yup.object().shape({
    organisationName: Yup.string().required('Organisation Name is required'),
    // customerTypes: customerTypesSchema,
    // customerCategory: customerCategorySchema,
    organisationType: Yup.string().required('Organisation Type is required'),
    otherType: Yup.string(),
    // customerAddress: addressSchema,
    primaryContactNo: Yup.string().required('Primary Contact No. is required').matches(/^\d{10}$/, 'Contact number must be 10 digits'),
    secondaryContactNo: Yup.string().matches(/^\d{10}$/, 'Contact number must be 10 digits'),
    emailPrimary: Yup.string().email('Invalid email format').required('Primary Email is required'),
    emailSecondary: Yup.string().email('Invalid email format'),
//     keyMobileNumbers: keyMobileNumbersSchema,
//     billingDetails: billingDetailsSchema,
//     deliveryDetails: deliveryDetailsSchema,
//     statutoryDetails: statutoryDetailsSchema,
//     bankDetails: bankDetailsSchema,
//     productSpecification: Yup.array().of(productSpecificationSchema),
//     paymentTerms: paymentTermsSchema,
//     officeUseOnly: officeUseOnlySchema,
});
