import { initValAddress } from '@prime-fresh/admin/modules';
import { PostBankDetails, PostBillingDetails, PostDeliveryDetails, PostKeyMobileNumbers, PostOfficeUseOnly, PostPaymentTerms, PostProductSpecification, PostStatutoryDetails } from '@prime-fresh/admin_api';

const initCustomerTypes = {
    id: '',
    name: '',
};

const initCustomerCategory = {
    id: '',
    name: '',
};

const initKeyMobileNumbers: PostKeyMobileNumbers = {
    accDeptFName: '',
    accDeptMName: '',
    accDeptLName: '',
    accDeptMobileNo: '',
    ownerFName: '',
    ownerMName: '',
    ownerLName: '',
    ownerMobileNo: '',
    mandiLicenceNo: '',
    mandiLicenceCopy: null,
    regiNo: '',
    regiCopy: null,
    electricityBill: '',
    consumenrNo: '',
    electricityBillCopy: null,
    notElectricityBillReason: '',
    customerBlacklisted: '',
    ifBlacklistedReason: '',
    blackListedBy: '',
    visitingCard: '',
    visitinContactNo: '',
    visitingCardCopy: null,
    notVisitingCardReason: '',
    ref1FName: '',
    ref1MName: '',
    ref1LName: '',
    ref1Address: initValAddress,
    ref1ContactNo: '',
    ref1Email: '',
    ref2FName: '',
    ref2MName: '',
    ref2LName: '',
    ref2Address: initValAddress,
    ref2ContactNo: '',
    ref2Email: '',
};

const initBillingDetails: PostBillingDetails = {
    billingName: '',
    contactPersonFName: '',
    contactPersonMName: '',
    contactPersonLName: '',
    commonlyKnownAs: '',
    billingAddress: initValAddress,
    billingAddressProofCopy: null,
    primaryContactNo: '',
    secondaryContactNo: '',
    emailPrimary: '',
    emailSecondary: '',
    billingFormatCopy: null,
};

const initDeliveryDetails: PostDeliveryDetails = {
    deliveryAddress: initValAddress,
    deliveryAddressProofCopy:'',
    deliveryTime: null,
    receivingPersonFName: '',
    receivingPersonMName: '',
    receivingPersonLName: '',
    primaryContactNo: '',
    secondaryContactNo: '',
    emailPrimary: '',
    emailSecondary: '',
};

const initStatutoryDetails: PostStatutoryDetails = {
    panNo: '',
    panCopy: null,
    aadharNo: '',
    addharCopy: null,
    gstn: '',
    regiCertificateCopy: null,
    billBookCopy: null,
    certificationsDetails: '',
    otherCertifications: '',
    corpRegiDetails: '',
    otherCorpRegiDetails: '',
    incorpoCertificateCopy: null,
    cinNo: '',
};

const initBankDetails: PostBankDetails = {
    ifCancelledCheque: '',
    notCancelledChequeReason: '',
    cancelledChequeCopy: null,
    accType: '',
    otherAccType: '',
    bankStatementCopy: null,
    bankAccHolderFName: '',
    bankAccHolderMName: '',
    bankAccHolderLName: '',
    bankName: '',
    bankBranch: '',
    bankAccNo: '',
    ifscCode: '',
    bankAddress: initValAddress,
};

const initProductSpecification: PostProductSpecification[] = [
    {
        articleName: '',
        specifications: '',
        parameters: '',
        packingMaterialSpec: '',
        rejectionCriteria: '',
        comment: '',
    },
];

const initPaymentTerms: PostPaymentTerms = {
    paymentMade: '',
    otherPaymentMade: '',
    paymentMode: '',
    otherPaymentMode: '',
    marginDeposit: '',
    rtv: '',
    agreementExecuted: '',
    lc: '',
    bg: '',
    securityDepoCheqNo: '',
    securityDepoAmt: 0,
    IELinAmt: 0,
    IELRecommendedBy: '',
    IELRecommendedDate: null,
    RELinAmt: 0,
    RELRecommendedBy: '',
    RELRecommendedDate: null,
    reason: '',
    docEvidenceCopy: null,
};

const initOfficeUseOnly: PostOfficeUseOnly = {
    proposerBDName: '',
    pflCoordinator: '',
    recommendedBy: '',
    dispatchLocationPfl: '',
    approvedBy: '',
    relationshipManager: '',
    avgBillingMonthly: 0,
    volumeMonthly: 0,
    customerVerification: '',
    verificationAgency: '',
    validityPeriod: '',
    dueDiligenceDone: '',
    creditWorthinessDue: '',
    keyAccountPersonAssigned: '',
    sinceWhen: '',
    ledgerCreatedDate: null,
    ledgerCreatedBy: '',
    ledgerVerifiedApprovedBy: '',
    additionalNotes: '',
    customerCode: '',
    createdBy: '',
    createdDate: null,
};

export const initValCustomer = {
    organisationName: '',
    customerTypes: initCustomerTypes,
    customerCategory: initCustomerCategory,
    organisationType: '',
    otherType: '',
    customerAddress: initValAddress,
    primaryContactNo: '',
    secondaryContactNo: '',
    emailPrimary: '',
    emailSecondary: '',
    keyMobileNumbers: initKeyMobileNumbers,
    billingDetails: initBillingDetails,
    deliveryDetails: initDeliveryDetails,
    statutoryDetails: initStatutoryDetails,
    bankDetails: initBankDetails,
    productSpecification: initProductSpecification,
    paymentTerms: initPaymentTerms,
    officeUseOnly: initOfficeUseOnly,
};
