export const initValLabourPaymentvoucher = {
    grnNo: null,
    companyName: null,
    debitCreditTo: null,
    payReceivedFrom: null,
    location: null,
    noOfLabours: 0,
    loadingDate: null,
    workLocation: null,
    contactNo: null,
    altContactNo: null,
    products: null,
    kyc: false,
    paymentMode: null,
    ratePerLabour: 0,
    totalAmt: 0,
    amtWords: null,
    receiverName: null,
    remark: null,
    anyAttachment: null,
}