export const initValLabourPaymentvoucher = {
    grnNo: '',
    companyName: '',
    debitCreditTo: '',
    payReceivedFrom: '',
    location: '',
    noOfLabours: 0,
    loadingDate: new Date(),
    workLocation: '',
    contactNo: '',
    altContactNo: '',
    products: '',
    paymentMode: '',
    ratePerLabour: 0,
    totalAmt: 0,
    amtWords: '',
    receiverName: '',
    anyAttachment: null,
}