import {
    ICustomer,
    ICustomerBankDetails,
    ICustomerBillingDetails,
    ICustomerDeliveryDetails,
    ICustomerKeyMobileNumbers,
    ICustomerOfficeUseOnly,
    ICustomerPaymentTerms,
    ICustomerProductSpecs,
    ICustomerStatutoryDetails
} from '../models';
import { initValAddress } from './address.initial-value';

const initKeyMobileNumbers: ICustomerKeyMobileNumbers = {
    accDeptFName: null,
    accDeptMName: null,
    accDeptLName: null,
    accDeptMobileNo: null,
    ownerFName: null,
    ownerMName: null,
    ownerLName: null,
    ownerMobileNo: null,
    mandiLicenceNo: null,
    mandiLicenceCopy: null,
    regiNo: null,
    regiCopy: null,
    electricityBill: null,
    consumenrNo: null,
    electricityBillCopy: null,
    notElectricityBillReason: null,
    customerBlacklisted: null,
    ifBlacklistedReason: null,
    blackListedBy: null,
    visitingCard: null,
    visitinContactNo: null,
    visitingCardCopy: null,
    notVisitingCardReason: null,
    ref1FName: null,
    ref1MName: null,
    ref1LName: null,
    ref1Address: initValAddress,
    ref1ContactNo: null,
    ref1Email: null,
    ref2FName: null,
    ref2MName: null,
    ref2LName: null,
    ref2Address: initValAddress,
    ref2ContactNo: null,
    ref2Email: null,
}

const initBillingDetails: ICustomerBillingDetails = {
    billingName: null,
    contactPersonFName: null,
    contactPersonMName: null,
    contactPersonLName: null,
    commonlyKnownAs: null,
    billingAddress: initValAddress,
    billingAddressProofCopy: null,
    primaryContactNo: null,
    secondaryContactNo: null,
    emailPrimary: null,
    emailSecondary: null,
    billingFormatCopy: null,
}

const initDeliveryDetails: ICustomerDeliveryDetails = {
    deliveryAddress: initValAddress,
    deliveryAddressProofCopy: null,
    deliveryTime: null,
    receivingPersonFName: null,
    receivingPersonMName: null,
    receivingPersonLName: null,
    primaryContactNo: null,
    secondaryContactNo: null,
    emailPrimary: null,
    emailSecondary: null,
}

const initStatutoryDetails: ICustomerStatutoryDetails = {
    panNo: null,
    panCopy: null,
    aadharNo: null,
    aadharCopy: null,
    gstn: null,
    regiCertificateCopy: null,
    billBookCopy: null,
    certificationsDetails: null,
    otherCertifications: null,
    corpRegiDetails: null,
    otherCorpRegiDetails: null,
    incorpoCertificateCopy: null,
    cinNo: null,
}

const initBankDetails: ICustomerBankDetails = {
    ifCancelledCheque: null,
    notCancelledChequeReason: null,
    cancelledChequeCopy: null,
    accType: null,
    otherAccType: null,
    bankStatementCopy: null,
    bankAccHolderFName: null,
    bankAccHolderMName: null,
    bankAccHolderLName: null,
    bankName: null,
    bankBranch: null,
    bankAccNo: null,
    ifscCode: null,
    bankAddress: initValAddress,
}

export const initProductSpecification: ICustomerProductSpecs = {
    articleName: null,
    specifications: null,
    parameters: null,
    packingMaterialSpec: null,
    rejectionCriteria: null,
    comment: null,
}


const initPaymentTerms: ICustomerPaymentTerms = {
    paymentMade: null,
    otherPaymentMade: null,
    paymentMode: null,
    otherPaymentMode: null,
    marginDeposit: null,
    rtv: null,
    agreementExecuted: null,
    lc: null,
    bg: null,
    securityDepoCheqNo: null,
    securityDepoAmt: 0,
    IELinAmt: 0,
    IELRecommendedBy: null,
    IELRecommendedDate: null,
    RELinAmt: 0,
    RELRecommendedBy: null,
    RELRecommendedDate: null,
    reason: null,
    docEvidenceCopy: null,
}

const initOfficeUseOnly: ICustomerOfficeUseOnly = {
    proposerBDName: null,
    recommendedBy: null,
    approvedBy: null,
    pflCoordinator: null,
    dispatchLocationPfl: null,
    relationshipManager: null,
    avgBillingMonthly: 0,
    volumeMonthly: 0,
    customerVerification: null,
    verificationAgency: null,
    validityPeriod: null,
    dueDiligenceDone: null,
    creditWorthinessDue: null,
    keyAccountPersonAssigned: null,
    sinceWhen: null,
    ledgerCreatedDate: null,
    ledgerCreatedBy: null,
    ledgerVerifiedApprovedBy: null,
    additionalNotes: null,
}

export const initValCustomer: Omit<ICustomer, 'id'> = {
    organisationName: null,
    customerTypes: null,
    customerCategory: null,
    organisationType: null,
    otherType: null,
    customerAddress: initValAddress,
    primaryContactNo: null,
    secondaryContactNo: null,
    emailPrimary: null,
    emailSecondary: null,
    keyMobileNumbers: initKeyMobileNumbers,
    billingDetails: initBillingDetails,
    deliveryDetails: initDeliveryDetails,
    statutoryDetails: initStatutoryDetails,
    bankDetails: initBankDetails,
    productSpecification: [initProductSpecification],
    paymentTerms: initPaymentTerms,
    officeUseOnly: initOfficeUseOnly
}
