import { Chip } from '@mui/material';
import { GridRenderCellParams } from '@mui/x-data-grid';
import { Address } from '@prime-fresh/common_api';
import { convertInTitleCase, formatAddress, getDocStatusColor } from '@prime-fresh/shared/modules';
import { CustomGridColDef } from '@prime-fresh/ui_shared';

export const vehicleDispatchRegisterColumns: CustomGridColDef[] = [
  {
    field: 'overAllStatus',
    headerName: 'Status',
    flex: 1,
    minWidth: 130,
    align: 'center',
    headerAlign: 'center',
    hide: false,
    isMobileVisible: true,
    renderCell: (params: GridRenderCellParams) => {
      const status = convertInTitleCase(params.row.overAllStatus || '');
      return (
        <Chip
          label={status}
          size="small"
          sx={{
            flex: 1,
            minWidth: 80,
            color: '#FFF',
            backgroundColor: getDocStatusColor(params.row.overAllStatus || ''),
          }}
        />
      );
    },
  },
  {
    field: 'createdBy',
    headerName: 'Created By',
    flex: 1,
    minWidth: 120,
    align: 'center',
    headerAlign: 'center',
    hide: false,
    valueGetter: (value: string) => (value ? convertInTitleCase(value || '') : ''),
  },
  {
    field: 'createdDate',
    headerName: 'Created Date',
    flex: 1,
    minWidth: 120,
    align: 'center',
    headerAlign: 'center',
    hide: false,
  },
  {
    field: 'createdTime',
    headerName: 'Created Time',
    flex: 1,
    minWidth: 120,
    align: 'center',
    headerAlign: 'center',
    hide: false,
  },
  {
    field: 'companyName',
    headerName: 'Company',
    flex: 1,
    minWidth: 200,
    align: 'center',
    headerAlign: 'center',
    valueGetter: (value: string) => (value ? value : '-'),
    hide: false,
  },
  {
    field: 'date',
    headerName: 'Date',
    minWidth: 100,
    flex: 1,
    align: 'center',
    headerAlign: 'center',
    hide: false,
    isMobileVisible: true,
    valueGetter: (value: string) => (value ? value : '-'),
  },
  {
    field: 'vehicleNo',
    type: 'string',
    headerName: 'Vehicle No',
    flex: 1,
    minWidth: 150,
    headerAlign: 'center',
    isMobileVisible: true,
    valueGetter: (value: string) => (value ? value : '-'),
  },
  {
    field: 'vehicleType',
    type: 'string',
    headerName: 'Vehicle No',
    flex: 1,
    minWidth: 150,
    headerAlign: 'center',
    valueGetter: (value: string) => (value ? value : '-'),
  },
  {
    field: 'driverName',
    type: 'string',
    headerName: 'Driver Name',
    flex: 1,
    minWidth: 150,
    headerAlign: 'center',
    valueGetter: (value: string) => (value ? value : '-'),
  },
  {
    field: 'driverMobNo',
    type: 'string',
    headerName: 'Driver Mob No',
    flex: 1,
    minWidth: 100,
    align: 'center',
    headerAlign: 'center',
    valueGetter: (value: string) => (value ? value : '-'),
  },
  {
    field: 'paymentDiscussed',
    type: 'number',
    headerName: 'Payment Discussed',
    flex: 1,
    minWidth: 100,
    align: 'center',
    headerAlign: 'center',
    valueGetter: (value: string) => (value ? value : '-'),
  },
  {
    field: 'transportationBillAmt',
    type: 'number',
    headerName: 'Transportation Bill Amount',
    flex: 1,
    minWidth: 100,
    align: 'center',
    headerAlign: 'center',
    valueGetter: (value: string) => (value ? value : '-'),
  },
  {
    field: 'advancePaid',
    type: 'number',
    headerName: 'Advance Paid Amount',
    flex: 1,
    minWidth: 100,
    align: 'center',
    headerAlign: 'center',
    valueGetter: (value: string) => (value ? value : '-'),
  },
  {
    field: 'clientName',
    type: 'string',
    headerName: 'Client Name',
    flex: 1,
    minWidth: 150,
    headerAlign: 'center',
    valueGetter: (value: string) => (value ? value : '-'),
  },
  {
    field: 'clientAddress',
    headerName: 'Client Address',
    flex: 1,
    minWidth: 200,
    headerAlign: 'center',
    valueGetter: (value: Address) => (value ? formatAddress(value) : '-'),
  },
  {
    field: 'receivingPerson',
    type: 'string',
    headerName: 'Receiving Person',
    flex: 1,
    minWidth: 150,
    headerAlign: 'center',
    valueGetter: (value: string) => (value ? value : '-'),
  },
  {
    field: 'outTime',
    type: 'string',
    headerName: 'Out Time',
    flex: 1,
    minWidth: 100,
    headerAlign: 'center',
    valueGetter: (value: string) => (value ? value : '-'),
  },
  {
    field: 'reachingTime',
    type: 'string',
    headerName: 'Reaching Time',
    flex: 1,
    minWidth: 100,
    headerAlign: 'center',
    valueGetter: (value: string) => (value ? value : '-'),
  },
  {
    field: 'netInwardQty',
    type: 'number',
    headerName: 'Net Inward Qty',
    flex: 1,
    minWidth: 100,
    align: 'center',
    headerAlign: 'center',
    valueGetter: (value: string) => (value ? value : '-'),
  },
  {
    field: 'rejection',
    type: 'number',
    headerName: 'Rejection',
    flex: 1,
    minWidth: 100,
    align: 'center',
    headerAlign: 'center',
    valueGetter: (value: string) => (value ? value : '-'),
  },
  {
    field: 'shrinkageDump',
    type: 'number',
    headerName: 'Shrinkage Dump',
    flex: 1,
    minWidth: 100,
    align: 'center',
    headerAlign: 'center',
    valueGetter: (value: string) => (value ? value : '-'),
  },
];
