import { ITranportPaymentVoucher } from '@prime-fresh/services';

export const transportPaymentVoucherInitialValue: Omit<ITranportPaymentVoucher, 'id'> = {
  grnNo: null,
  companyName: '',
  debitCreditTo: null,
  payReceivedFrom: null,
  location: null,
  driverName: null,
  contactNo: null,
  altContactNo: null,
  vehicleNo: null,
  dispatchLocation: null,
  destinationLocation: null,
  products: [],
  paymentMode: null,
  freightAmt: null,
  actualAmt: null,
  advanceAmt: null,
  decidedAmt: null,
  deductionAmt: null,
  extraAmt: null,
  finalPayableAmt: null,
  totalPayableAmt: null,
  amtWords: null,
  receiverName: null,
  remark: null,
  kyc: false,
  anyAttachment: [],
};
