export const filterTitles = {
    grnNo: null,
    locationType: "cc",
    grnType: "purchase",
    purchaseType: "fix purchase",
    purchaseInstructionsBy: "abcd",
    companyName: "xyz",
    dealSlipId: null,
    purchaseLocation: null,
    source:"farmer",
    vendorId: null,
    farmerId:null,
    vendorcategoryId:null,
    vendorsubcategoryId:null,
    productId:null,
    productCategoryId:null,
    productSubCategoryId:null,
    dateFrom:null,
    dateTo:null,
}